### PR TITLE
Make package composer 2 compatible

### PR DESCRIPTION
**Pull request by BramG**
Didnt, try to push yet.
But the composer require didn't fail anymore.

Tested with:
curl https://getcomposer.org/composer-2.phar --output composer-2.phar

### CODE REVIEW

**Comment by Elendev** [comment]
Hi @BramG, thanks for this PR!
Can you also update the GH Actions build to support Composer 2 in the build matrix?

https://github.com/Elendev/nexus-composer-push/blob/master/.github/workflows/testing-and-cs.yaml#L27

Thanks!

**Comment by BramG** [comment]
@Elendev I need some help, looking at the documentation https://github.com/marketplace/actions/setup-php-action using v2 should work but it isn't. I tried to execute the composer require with composer 2 locally and it works perfectly...

**Comment by BramG** [comment]
It's green!

**Review by Elendev — APPROVED** [review]
Thank you @BramG for your contribution!

**Comment by Elendev** [comment]
@BramG I've released `0.3.0`, thanks!

**Pull request merged**
