### PR TITLE
Detect when the package is installed globally

### PR DESCRIPTION
**Pull request by mveyrenc**
This merge request makes this composer command works when it is install in global and not in the project.

### CODE REVIEW

**Comment by mveyrenc** [comment]
Hi, I revert all the code formatting.

Don't hesitate to come back to me if you get any more feedback.

We use your plugin by install it in global, to avoid to add its dependencies to the project; Like this :
```
composer global require --dev elendev/nexus-composer-push
composer nexus-push ...
```


Thanks!

**Comment by Elendev** [comment]
@mveyrenc are you sure you pushed your commit? I only see one commit, and the formatting is still there.
As soon as it's done I'll merge it.
Thanks!

**Comment by mveyrenc** [comment]
Sorry my IDE format code before commit, this time it's OK.

**Comment by Elendev** [comment]
Thanks!

**Pull request merged**
