### PR TITLE
Include Guzzle manually

### PR DESCRIPTION
**Pull request by tvanrielwendrich**
This should  fix the  plugin when  installed  globally,  It's a terribly
nasty hack. But it's the only thing that will work when Composer doesn't
get it's crap together  and actually gives us a callback or exposes some
API we can call for autoloading.

The problem here lies in  the fact that Composer loads extra files (such
as a classmap) post-plugin. so when we are loaded, the function files of
Guzzle aren't loaded.  This can be done by  manually  calling require on
those files.

Luckily Guzzle already  has a system in place to prevent  double-loading
their functions and we can safely include it.

Github issues:
Fix Elendev/nexus-composer-push#11

Signed-off-by: Ted van Riel <tvanriel@wendrich.com>

### CODE REVIEW

**Comment by Elendev** [comment]
Thanks @tvanrielwendrich for this contribution!

> This should fix the plugin when installed globally, It's a terribly
nasty hack. But it's the only thing that will work when Composer doesn't
get it's crap together and actually gives us a callback or exposes some
API we can call for autoloading.

I totally agree. Let's hope a fix will come to composer, but in the meantime, this looks more robust than what's currently in place.

**Comment by Elendev** [comment]
@tvanrielwendrich I've released the version 0.1.1 with your PR.

**Comment by xrobau** [comment]
Note that this has broken everyone who does NOT have it installed globally.

**Comment by jpruiz114** [comment]
How can one install Guzzle globally? I am getting this error when trying to push a new version of a library to Nexus. Thanks.

**Pull request merged**
