### PR TITLE
Be more explicit when ignoring dirs and allow file ignores

### PR DESCRIPTION
**Pull request by Hodgy**
We have issues with files that contain `test` in their name being excluded from packages when we specify `test` as an ignore directory due it to using `notPath` filter under the hood.

Have modified it so that directory ignores are handle via the `exclude` filter so it's more explicit and adding a new option to allow use of the `notPath` filter with the ignore-files option.

### CODE REVIEW

**Comment by Elendev** [comment]
Thank you for this PR !

I was wondering if it's possible to use the capabilities of the `finder` component to have a simple option allowing to ignore both files and directories (and using `-f` to ignore file seems counter intuitive).

After some tests, we can simply replace the `$finder->exclude("directory")` by `$finder->notPath("directory-or-file")`.

This way we have a simple `--ignore` option to ignore both directories (`--ignore dirname`) and files (`--ignore dirname/filename.txt`). We will even be able to ignore by pattern : `--ignore dirname/*.tmp`.

What I propose is to : 
 * add the `--ignore` option (and using the `-i` shortcut)
 * add a `ignore` configuration entry
 * mark the `--ignore-dirs` option
 * mark (in a way or an other) `ignore-dirs` configuration as deprecated.

Under the hood, `--ignore-dirs` will use `--ignore` and the deprecated option will be removed on the first major release (v1.0).

@Hodgy what are your thought on this ?

**Comment by Hodgy** [comment]
Have discussed your proposal with my colleague ( @sdh100shaun) and we agree. 

However we think we would still come across the same issue if we just used `$finder->notPath("directory-or-file")` it all. Adding `--ignore test` would still exclude the the test directory but also our `GetLatestFeeType.php` file would be excluded due to having `test` within the filename. 

A solution to this would be something along the lines of 

```
$ignores = $this->getIgnores();
foreach ($ignores as $ignore) {
    if ($filesystem->isDirectory($ignore)) {
        $finder->exclude($ignore)
    } else {
        $finder->notPath($ignore)
    }
}
```

It would be extra system calls but we can't see the number of ignores being passed ever being high enough to cause a noticeable performance issue.  

@Elendev How do you feel about this?

**Comment by Elendev** [comment]
I see your problem, I've been able to reproduce it.

I'm not sure that your proposition (using `$filesystem->isDirectory($ignore)`) will work as `$ignore` can be a pattern (`tests/*.php`) and I don't know how it's detected (as a file / a directory or none of the above ?). Can you test this specific case ? And the other way around too, with a pattern for directory, test if it's considered as a file ?

For your specific problem I've tried with `--ignore test/` and I've been able to filter only a `test` directory without filtering a `GetLatestFeeType.php` file. On the other hand, I'm not totally convinced by `--ignore test/`, what do you think about this @Hodgy and @sdh100shaun?

**Comment by Hodgy** [comment]
We can ignore my modified proposal. Apparently my brain was failing me yesterday and there are no issues with using "test/", for some reason I thought i tested this and it still excluded the file. 

I don't think it's an issue to do `--ignore test/` as this way is used in other cli commands.

**Comment by Elendev** [comment]
@Hodgy nice, let's go for it then :+1:

**Comment by Hodgy** [comment]
Awesome. I'll get working on it.

**Comment by sdh100shaun** [comment]
Sounds great, this is helping us no end thanks @Elendev  :-)

**Comment by Hodgy** [comment]
@Elendev Have made the changes in your proposal if you want to take a look :D

**Comment by Elendev** [comment]
@Hodgy nice work !

I'll merge (and release a new version) as soon as the conflict is resolved.

**Comment by Hodgy** [comment]
@Elendev Awesome, have just pushed a commit to resolve conflicts :)

**Comment by Elendev** [comment]
Thank you for your work @Hodgy and @sdh100shaun ! I'll release a new version.

**Pull request merged**
