### PR TITLE
allow ignore by .gitattributes

### PR DESCRIPTION
**Pull request by zhwei**

### CODE REVIEW

**Comment by Elendev** [comment]
Thank you @zhwei for this PR !

I think it would be great to add the the option to set it in the nexus-extras like this:

```
{
    "extra": {
        "nexus-push": {
            "ignore-by-git-attributes": true
        }
    }
}
```

Otherwise, seems perfect.

**Comment by zhwei** [comment]
@Elendev updated

**Comment by Elendev** [comment]
LGTM, thanks @zhwei, I'll release a new version as soon as #8 is merged in master.

**Comment by zhwei** [comment]
thanks @Elendev

**Pull request merged**
