### PR TITLE
Fixes #15 - Use the Vendor directory

### LINKED ISSUE #15: 'Require Guzzle Functions Manually' is broken
The code is (taking just one example):

        $guzzlepromisesfunctions = $composer->getConfig()->get('home') . '/vendor/guzzlehttp/promises/src/functions_include.php';
        if (!file_exists($guzzlepromisesfunctions)) {
            throw new FileNotFoundException("guzzlehttp/promises/src/functions.php not found, is guzzle installed?");
        }

Firstly, it's checking for `functions_include.php` and then saying `functions.php` is missing, and secondly `$composer->getConfig()->get('home')` returns the $HOME directory - eg /home/fred.

### PR DESCRIPTION
**Pull request by xrobau**
This also displays the correct file that is not present.

### CODE REVIEW

**Comment by tvanrielwendrich** [comment]
Hi, I haven't tested this fix. but does that still work in global context? if not, we could check if we are running globally and determine whether we should find guzzle in local or global.

**Comment by xrobau** [comment]
No. I discovered that this was an attempt to fix that other issue after I had already submitted the pull request. As this package is 100% broken without it, I thought that it would be better to fix it first and then try to readdress the other issue later.

With the path, if you can't find a file, you should always display the full path of the file. Otherwise it's impossible to find where it was looking. This bug is a prime example of why you want to do that! It was saying a file didn't exist, but it did 8)

**Comment by tvanrielwendrich** [comment]
Okay, I have had a few more minutes to think about it. and I now know why it is broken. 
Despite it running in local context, it will always look for guzzle in global context. Correct? 
Perhaps a decent fix would indeed then be to determine whether we should take from local or global depending on what context the code is running in at that time.

I haven't looked at the `vendor-dir` thing. but I assume it returns the local one always. Because that is why this was broken first. What if we do a substring check to determine if `__FILE__` starts with `home`, and then look for guzzle in global. and if not, look for guzzle in local.

**Comment by xrobau** [comment]
No, that's making an assumption. I'm almost certain that there is some way to ask composer where it is running, but I think a reasonably accurate way of doing so would be to check if __DIR__ is contained within getConfig()->get('home') or something like that. Making an assumption that home starts with /home breaks for lots of things (eg, root, www-user, etc)

**Comment by xrobau** [comment]
Sorry for inadvertent markdown, on mobile and watching tv 8)

**Comment by tvanrielwendrich** [comment]
>Sorry for inadvertent markdown, on mobile and watching tv 8)
Don't worry. I know it's past work hours for Australia.

getConfig(home) doesn't refer to `~`, but rather to `$COMPOSER_HOME` which (according to the documentation) refers to `~/.composer` or `~/.config/composer` depending if you are running XDG or not.

**Comment by xrobau** [comment]
Yes, sorry, I was wrong there, even after looking at it three times. But a strpos for DIR in `get('home')` === 0 should be enough. But I'm still pretty sure there's a way to ask composer.

I'll leave it with you to sort out 8)

**Comment by Elendev** [comment]
Hi @xrobau and @tvanrielwendrich, I'm sorry I wasn't able to test enough before merging the PR that lead to this issue.
I don't have time to take a look at this issue but I will gladly merge any PR that fixes this issue.
Let me know when this PR is ready to merge.

**Comment by qbaze** [comment]
Hello guys,

Regarding global and no global context, it looks composer-getConfig() is context aware and return correct paths. I've checked it. However, I'm not the php specialist and don't really understand why you do this ugly hack :)
The fix works for me and I think should be accepted but I don't know your process @Elendev . 
Also I have some fixes regarding #17 and would like to commit.

Best,
Piotr

**Comment by Elendev** [comment]
Hi @qbaze, currently I don't have a special process for this project, it's more like "if it works it works", so a little bit of hack to fix the issue of the previous PR is ok for me.
I'll try to make time to do proper testing.

**Pull request merged**
