### PR TITLE
Need to add a default return for getting from composer extras

### PR DESCRIPTION
**Pull request by Hodgy**

### CODE REVIEW

**Comment by Elendev** [comment]
LGTM, let me know when you need a new release (if you have other modifications to do in the meantime).

**Comment by Hodgy** [comment]
Thanks! I don't think we have any other modifications we need. Though we are only in the early stages of moving to nexus so we may find some more over the next few days. I do want to try and add some tests though :D but feel free to do a new release whenever you have a chance.

**Comment by Elendev** [comment]
Done, v0.0.4 has been released.
I plan to add code formatting checks using Github Actions, if you add some unit testings it can be automatically executed the same way (it can be a great way to test this feature).

**Comment by Hodgy** [comment]
Ahh nice! I will see how I get on with them.

**Pull request merged**
